// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDID5-2jhdUYgqjn1usJYtxFykSj_-fVxM',
    appId: '1:111188604791:web:86328c8c69acaed5fb9372',
    messagingSenderId: '111188604791',
    projectId: 'meka-1213b',
    authDomain: 'meka-1213b.firebaseapp.com',
    storageBucket: 'meka-1213b.firebasestorage.app',
    measurementId: 'G-73VEX7ZLDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOcz1BkBh1GzKOw8rl_4cK1GPONkPbAc4',
    appId: '1:111188604791:android:988e6dc80e7d31ebfb9372',
    messagingSenderId: '111188604791',
    projectId: 'meka-1213b',
    storageBucket: 'meka-1213b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM0Jdsp6GEFQy1Ltp44EJ83P3N95Y_tMs',
    appId: '1:111188604791:ios:b6bcdc2ace5d5a19fb9372',
    messagingSenderId: '111188604791',
    projectId: 'meka-1213b',
    storageBucket: 'meka-1213b.firebasestorage.app',
    iosBundleId: 'com.example.meka',
  );
}
